// Code generated by internal/errtrace/codegen. DO NOT EDIT.
//
// Source: internal/errtrace/codes.yaml
// Regenerate: nix run nixpkgs#go -- run ./internal/errtrace/codegen
//
// This file is the bridge between the human-curated codes.yaml and
// runtime/test consumers. See codegen/main.go for the full contract.

package errtrace

// CodeMeta describes a single error code's static metadata. Populated
// at generate-time from codes.yaml; never mutated at runtime.
type CodeMeta struct {
	// Const is the Go identifier of the matching const in codes.go
	// (e.g. "ErrConfigOpen"). Used by the P1.4 registry test to
	// cross-check that codes.yaml and codes.go stay in sync.
	Const string

	// Block is the human-readable group name (e.g. "Config", "Store").
	// Useful for grouping codes in UI/error-registry renderings.
	Block string

	// Prefix is the ER-XXX prefix shared by every code in the block
	// (e.g. "ER-CFG"). Lets callers do prefix-matching without
	// re-parsing the Code value.
	Prefix string

	// Description is a one-line summary of when the code fires.
	// Mirrors the corresponding entry in spec/21-app/06-error-registry.md.
	Description string
}

// RegisteredCodes is the canonical set of every error code declared
// in codes.yaml. Keyed by the Code value (e.g. errtrace.ErrConfigOpen).
//
// Entries are sorted by Code string at generation time; iteration
// order over the map is still randomised by the runtime — callers
// that need deterministic order should range over a sorted key slice.
var RegisteredCodes = map[Code]CodeMeta{
	ErrAccountTestFailed:          {Const: "ErrAccountTestFailed", Block: "Accounts", Prefix: "ER-ACC", Description: "Test Connection failed against the configured IMAP endpoint.\nThe UI must surface the underlying reason and instruct the user\nto verify the password via raw IMAP before assuming the app is\nat fault. See spec/21-app/03-issues/solved/01-imap-auth-failed-wrong-password.md.\n"},
	ErrAccountPasswordSanitized:   {Const: "ErrAccountPasswordSanitized", Block: "Accounts", Prefix: "ER-ACC", Description: "Non-fatal warning — the configured password contained hidden\nUnicode (zero-width chars, RTL marks, etc.) that was stripped\nduring load. Surface as a one-time toast so the user knows the\nstored password differs from what they pasted. See\nspec/21-app/03-issues/solved/03-imap-auth-failed-hidden-unicode.md.\n"},
	ErrBrowserLaunch:              {Const: "ErrBrowserLaunch", Block: "Browser", Prefix: "ER-BRW", Description: "exec.Cmd.Start of the browser binary failed."},
	ErrBrowserNotFound:            {Const: "ErrBrowserNotFound", Block: "Browser", Prefix: "ER-BRW", Description: "Configured browser binary was not on PATH."},
	ErrBrowserDedupHit:            {Const: "ErrBrowserDedupHit", Block: "Browser", Prefix: "ER-BRW", Description: "URL was suppressed by the dedup window (sentinel, not a true error)."},
	ErrBrowserUrlInvalid:          {Const: "ErrBrowserUrlInvalid", Block: "Browser", Prefix: "ER-BRW", Description: "Target URL failed pre-launch validation."},
	ErrBrowserIncognitoFlag:       {Const: "ErrBrowserIncognitoFlag", Block: "Browser", Prefix: "ER-BRW", Description: "Incognito flag for the configured browser is unknown."},
	ErrConfigOpen:                 {Const: "ErrConfigOpen", Block: "Config", Prefix: "ER-CFG", Description: "Could not open the config file (missing, permission denied, etc.)."},
	ErrConfigDecode:               {Const: "ErrConfigDecode", Block: "Config", Prefix: "ER-CFG", Description: "Config file present but YAML/TOML parsing failed."},
	ErrConfigEncode:               {Const: "ErrConfigEncode", Block: "Config", Prefix: "ER-CFG", Description: "Failed to serialise config back to disk."},
	ErrConfigValidate:             {Const: "ErrConfigValidate", Block: "Config", Prefix: "ER-CFG", Description: "Config decoded but a field violates schema rules."},
	ErrConfigPasswordCrypt:        {Const: "ErrConfigPasswordCrypt", Block: "Config", Prefix: "ER-CFG", Description: "Encrypt/decrypt step on stored account password failed."},
	ErrConfigAccountDup:           {Const: "ErrConfigAccountDup", Block: "Config", Prefix: "ER-CFG", Description: "Two accounts share the same alias (must be unique)."},
	ErrConfigAccountMissing:       {Const: "ErrConfigAccountMissing", Block: "Config", Prefix: "ER-CFG", Description: "Lookup for an alias returned no matching account."},
	ErrConfigSchemaMigration:      {Const: "ErrConfigSchemaMigration", Block: "Config", Prefix: "ER-CFG", Description: "config.json schema migration step failed (FromVersion → ToVersion)."},
	ErrCliUsage:                   {Const: "ErrCliUsage", Block: "CLI", Prefix: "ER-CLI", Description: "Generic usage error (unknown subcommand, missing positional arg)."},
	ErrCliFlagConflict:            {Const: "ErrCliFlagConflict", Block: "CLI", Prefix: "ER-CLI", Description: "Two mutually exclusive flags were both supplied."},
	ErrCliMissingRequiredArg:      {Const: "ErrCliMissingRequiredArg", Block: "CLI", Prefix: "ER-CLI", Description: "A required flag/positional argument was omitted."},
	ErrCliInteractiveAborted:      {Const: "ErrCliInteractiveAborted", Block: "CLI", Prefix: "ER-CLI", Description: "User pressed Ctrl-C / EOF mid-prompt."},
	ErrCoreInvalidArgument:        {Const: "ErrCoreInvalidArgument", Block: "Core", Prefix: "ER-COR", Description: "Caller passed an argument outside the documented range."},
	ErrCoreNotImplemented:         {Const: "ErrCoreNotImplemented", Block: "Core", Prefix: "ER-COR", Description: "Code path is reserved for a future slice but not yet implemented."},
	ErrCoreContextCancelled:       {Const: "ErrCoreContextCancelled", Block: "Core", Prefix: "ER-COR", Description: "Operation aborted because ctx.Done() fired."},
	ErrCorePathOutsideData:        {Const: "ErrCorePathOutsideData", Block: "Core", Prefix: "ER-COR", Description: "A file path resolved outside the application's data directory."},
	ErrCoreClockSkew:              {Const: "ErrCoreClockSkew", Block: "Core", Prefix: "ER-COR", Description: "Detected wall-clock time moved backwards unexpectedly."},
	ErrCoreAccountRemoveRollback:  {Const: "ErrCoreAccountRemoveRollback", Block: "Core", Prefix: "ER-COR", Description: "Accounts.Remove rollback failed — could not re-INSERT the deleted WatchState row after a config.json revert."},
	ErrCoreAccountRenameRollback:  {Const: "ErrCoreAccountRenameRollback", Block: "Core", Prefix: "ER-COR", Description: "Accounts.Rename rollback failed — could not restore the prior Alias on the WatchState row after a config.json revert."},
	ErrCoreAccountUpdateRollback:  {Const: "ErrCoreAccountUpdateRollback", Block: "Core", Prefix: "ER-COR", Description: "Accounts.Update rollback failed — could not re-load the prior config.json snapshot after a credential test rejected the new values."},
	ErrDbOpen:                     {Const: "ErrDbOpen", Block: "Store", Prefix: "ER-DB", Description: "sql.Open or initial PRAGMA setup failed."},
	ErrDbMigrate:                  {Const: "ErrDbMigrate", Block: "Store", Prefix: "ER-DB", Description: "Schema migration step failed."},
	ErrDbInsertEmail:              {Const: "ErrDbInsertEmail", Block: "Store", Prefix: "ER-DB", Description: "UpsertEmail / InsertEmail write failed."},
	ErrDbQueryEmail:               {Const: "ErrDbQueryEmail", Block: "Store", Prefix: "ER-DB", Description: "SELECT against the Emails table failed."},
	ErrDbInsertUrl:                {Const: "ErrDbInsertUrl", Block: "Store", Prefix: "ER-DB", Description: "OpenedUrls write failed."},
	ErrDbQueryUrl:                 {Const: "ErrDbQueryUrl", Block: "Store", Prefix: "ER-DB", Description: "SELECT against OpenedUrls failed."},
	ErrDbWatchState:               {Const: "ErrDbWatchState", Block: "Store", Prefix: "ER-DB", Description: "WatchState read/write failed."},
	ErrDbUniqueViolation:          {Const: "ErrDbUniqueViolation", Block: "Store", Prefix: "ER-DB", Description: "SQLite UNIQUE constraint violation surfaced from a write."},
	ErrDbFkViolation:              {Const: "ErrDbFkViolation", Block: "Store", Prefix: "ER-DB", Description: "SQLite FOREIGN KEY constraint violation surfaced from a write."},
	ErrDbBusy:                     {Const: "ErrDbBusy", Block: "Store", Prefix: "ER-DB", Description: "SQLite SQLITE_BUSY returned after the busy_timeout window."},
	ErrDbReadOnly:                 {Const: "ErrDbReadOnly", Block: "Store", Prefix: "ER-DB", Description: "Write attempted against a database opened read-only."},
	ErrDbCorrupt:                  {Const: "ErrDbCorrupt", Block: "Store", Prefix: "ER-DB", Description: "SQLite SQLITE_CORRUPT — file integrity check failed."},
	ErrEmailsListInvalidLimit:     {Const: "ErrEmailsListInvalidLimit", Block: "Emails", Prefix: "ER-EML", Description: "ListEmailsOptions.Limit was negative or above the cap."},
	ErrEmailsGetNotFound:          {Const: "ErrEmailsGetNotFound", Block: "Emails", Prefix: "ER-EML", Description: "Get(alias, uid) returned no row — caller passed a stale UID."},
	ErrEmailsRefresherUnwired:     {Const: "ErrEmailsRefresherUnwired", Block: "Emails", Prefix: "ER-EML", Description: "Refresh called before WithRefresher injected a Refresher (bootstrap gap)."},
	ErrEmailsLifecycleNotFound:    {Const: "ErrEmailsLifecycleNotFound", Block: "Emails", Prefix: "ER-EML", Description: "Delete/Undelete reported zero RowsAffected for a non-empty UID set — UIDs not present for this alias."},
	ErrEmailsDeleteAlreadyDeleted: {Const: "ErrEmailsDeleteAlreadyDeleted", Block: "Emails", Prefix: "ER-EML", Description: "Reserved — strict-mode Delete called on an already-soft-deleted UID (idempotent path does not surface this today)."},
	ErrEmailsUndeleteNotDeleted:   {Const: "ErrEmailsUndeleteNotDeleted", Block: "Emails", Prefix: "ER-EML", Description: "Reserved — strict-mode Undelete called on a UID whose DeletedAt was already NULL (idempotent path does not surface this today)."},
	ErrExportOpenFile:             {Const: "ErrExportOpenFile", Block: "Exporter", Prefix: "ER-EXP", Description: "Could not create the output file."},
	ErrExportWriteRow:             {Const: "ErrExportWriteRow", Block: "Exporter", Prefix: "ER-EXP", Description: "Failed to encode/write a row to the export stream."},
	ErrExportFlush:                {Const: "ErrExportFlush", Block: "Exporter", Prefix: "ER-EXP", Description: "Final flush/Close on the export stream failed."},
	ErrExportNoData:               {Const: "ErrExportNoData", Block: "Exporter", Prefix: "ER-EXP", Description: "Export query returned zero rows (advisory)."},
	ErrMailDial:                   {Const: "ErrMailDial", Block: "Mail", Prefix: "ER-MAIL", Description: "TCP/TLS dial to the IMAP server failed."},
	ErrMailLogin:                  {Const: "ErrMailLogin", Block: "Mail", Prefix: "ER-MAIL", Description: "AUTHENTICATE / LOGIN command rejected."},
	ErrMailFetchUid:               {Const: "ErrMailFetchUid", Block: "Mail", Prefix: "ER-MAIL", Description: "UID FETCH command failed or returned malformed data."},
	ErrMailParseEnvelope:          {Const: "ErrMailParseEnvelope", Block: "Mail", Prefix: "ER-MAIL", Description: "Could not parse the envelope of a fetched message."},
	ErrMailWriteEml:               {Const: "ErrMailWriteEml", Block: "Mail", Prefix: "ER-MAIL", Description: "Writing the .eml payload to disk failed."},
	ErrMailLogout:                 {Const: "ErrMailLogout", Block: "Mail", Prefix: "ER-MAIL", Description: "LOGOUT command failed (non-fatal but logged)."},
	ErrMailTLSHandshake:           {Const: "ErrMailTLSHandshake", Block: "Mail", Prefix: "ER-MAIL", Description: "TLS handshake against the IMAP endpoint failed."},
	ErrMailTimeout:                {Const: "ErrMailTimeout", Block: "Mail", Prefix: "ER-MAIL", Description: "Per-command IMAP deadline exceeded."},
	ErrMailIdleUnsupported:        {Const: "ErrMailIdleUnsupported", Block: "Mail", Prefix: "ER-MAIL", Description: "Server advertised no IDLE capability; falling back to polling."},
	ErrMailSelectMailbox:          {Const: "ErrMailSelectMailbox", Block: "Mail", Prefix: "ER-MAIL", Description: "SELECT (mailbox open) command failed after a successful login."},
	ErrRulePatternInvalid:         {Const: "ErrRulePatternInvalid", Block: "Rules", Prefix: "ER-RUL", Description: "Rule pattern failed to compile (invalid regex/glob)."},
	ErrRuleNotFound:               {Const: "ErrRuleNotFound", Block: "Rules", Prefix: "ER-RUL", Description: "Lookup by id/name returned no matching rule."},
	ErrRuleDuplicate:              {Const: "ErrRuleDuplicate", Block: "Rules", Prefix: "ER-RUL", Description: "Attempted to insert a rule with a name that already exists."},
	ErrRuleEvaluate:               {Const: "ErrRuleEvaluate", Block: "Rules", Prefix: "ER-RUL", Description: "Runtime error during rule evaluation against an email."},
	ErrRuleSeedDefault:            {Const: "ErrRuleSeedDefault", Block: "Rules", Prefix: "ER-RUL", Description: "Seeding the default rule-set on first run failed."},
	ErrRuleRenameNoop:             {Const: "ErrRuleRenameNoop", Block: "Rules", Prefix: "ER-RUL", Description: "Rename called with newName equal to oldName (no-op rejected; caller bug)."},
	ErrRuleReorderMismatch:        {Const: "ErrRuleReorderMismatch", Block: "Rules", Prefix: "ER-RUL", Description: "Reorder input is not a permutation of current rule names (missing, extra, or duplicate names)."},
	ErrSettingsConstruct:          {Const: "ErrSettingsConstruct", Block: "Settings", Prefix: "ER-SET", Description: "NewSettingsService construction failed (missing dependency)."},
	ErrSettingsPollSeconds:        {Const: "ErrSettingsPollSeconds", Block: "Settings", Prefix: "ER-SET", Description: "PollSeconds value outside the allowed range."},
	ErrSettingsTheme:              {Const: "ErrSettingsTheme", Block: "Settings", Prefix: "ER-SET", Description: "Theme value not one of the allowed palette identifiers."},
	ErrSettingsUrlScheme:          {Const: "ErrSettingsUrlScheme", Block: "Settings", Prefix: "ER-SET", Description: "URL scheme rule rejects the candidate."},
	ErrSettingsChromePath:         {Const: "ErrSettingsChromePath", Block: "Settings", Prefix: "ER-SET", Description: "Configured Chrome/Chromium path is not executable."},
	ErrSettingsIncognitoArg:       {Const: "ErrSettingsIncognitoArg", Block: "Settings", Prefix: "ER-SET", Description: "Incognito CLI argument template is malformed."},
	ErrSettingsLocalhostUrls:      {Const: "ErrSettingsLocalhostUrls", Block: "Settings", Prefix: "ER-SET", Description: "localhost URL setting violates the gate rule."},
	ErrSettingsCompositeRule:      {Const: "ErrSettingsCompositeRule", Block: "Settings", Prefix: "ER-SET", Description: "A composite settings rule (multiple fields) failed validation."},
	ErrSettingsPersist:            {Const: "ErrSettingsPersist", Block: "Settings", Prefix: "ER-SET", Description: "Persisting settings to disk failed."},
	ErrSettingsConcurrentEdit:     {Const: "ErrSettingsConcurrentEdit", Block: "Settings", Prefix: "ER-SET", Description: "Detected a stale revision token on save (concurrent edit)."},
	ErrSettingsDetectChromeStat:   {Const: "ErrSettingsDetectChromeStat", Block: "Settings", Prefix: "ER-SET", Description: "os.Stat probe of the candidate Chrome binary failed."},
	ErrSettingsEventDropped:       {Const: "ErrSettingsEventDropped", Block: "Settings", Prefix: "ER-SET", Description: "Settings change event could not be published (bus full)."},
	ErrSettingsRetentionDays:      {Const: "ErrSettingsRetentionDays", Block: "Settings", Prefix: "ER-SET", Description: "RetentionDays value outside the allowed range."},
	ErrSettingsDensity:            {Const: "ErrSettingsDensity", Block: "Settings", Prefix: "ER-SET", Description: "UI density value not one of the allowed identifiers."},
	ErrToolsInvalidArgument:       {Const: "ErrToolsInvalidArgument", Block: "Tools", Prefix: "ER-TLS", Description: "Generic invalid argument to a tool subcommand."},
	ErrToolsReadFetchFailed:       {Const: "ErrToolsReadFetchFailed", Block: "Tools", Prefix: "ER-TLS", Description: "Tools.Read could not fetch the requested email."},
	ErrToolsDiagnoseAborted:       {Const: "ErrToolsDiagnoseAborted", Block: "Tools", Prefix: "ER-TLS", Description: "Tools.Diagnose aborted before completing checks."},
	ErrToolsExportPathExists:      {Const: "ErrToolsExportPathExists", Block: "Tools", Prefix: "ER-TLS", Description: "Tools.Export refused to overwrite an existing path."},
	ErrToolsOpenUrlEmpty:          {Const: "ErrToolsOpenUrlEmpty", Block: "Tools", Prefix: "ER-TLS", Description: "open-url called with empty URL string."},
	ErrToolsOpenUrlTooLong:        {Const: "ErrToolsOpenUrlTooLong", Block: "Tools", Prefix: "ER-TLS", Description: "URL exceeds maximum length cap."},
	ErrToolsOpenUrlMalformed:      {Const: "ErrToolsOpenUrlMalformed", Block: "Tools", Prefix: "ER-TLS", Description: "URL failed url.Parse (syntax error)."},
	ErrToolsOpenUrlScheme:         {Const: "ErrToolsOpenUrlScheme", Block: "Tools", Prefix: "ER-TLS", Description: "URL scheme not in the allowed set."},
	ErrToolsOpenUrlLocalhost:      {Const: "ErrToolsOpenUrlLocalhost", Block: "Tools", Prefix: "ER-TLS", Description: "URL points to localhost and the localhost gate is closed."},
	ErrToolsOpenUrlPrivateIp:      {Const: "ErrToolsOpenUrlPrivateIp", Block: "Tools", Prefix: "ER-TLS", Description: "URL resolves to a private IP and the private-IP gate is closed."},
	ErrToolsOpenUrlNoBrowser:      {Const: "ErrToolsOpenUrlNoBrowser", Block: "Tools", Prefix: "ER-TLS", Description: "No browser is configured for the URL scheme."},
	ErrToolsOpenUrlLaunchFailed:   {Const: "ErrToolsOpenUrlLaunchFailed", Block: "Tools", Prefix: "ER-TLS", Description: "Browser launch returned a non-zero exit before the URL opened."},
	ErrUiThemeUnknownToken:        {Const: "ErrUiThemeUnknownToken", Block: "UI", Prefix: "ER-UI", Description: "Theme code requested a token name that doesn't exist."},
	ErrUiStateLoad:                {Const: "ErrUiStateLoad", Block: "UI", Prefix: "ER-UI", Description: "Failed to read persisted view state from disk."},
	ErrUiStateSave:                {Const: "ErrUiStateSave", Block: "UI", Prefix: "ER-UI", Description: "Failed to write persisted view state to disk."},
	ErrUiFormValidation:           {Const: "ErrUiFormValidation", Block: "UI", Prefix: "ER-UI", Description: "A user-entered form field failed inline validation."},
	ErrUiViewRender:               {Const: "ErrUiViewRender", Block: "UI", Prefix: "ER-UI", Description: "A view's render path returned an error (unrecoverable for that frame)."},
	ErrUiClipboard:                {Const: "ErrUiClipboard", Block: "UI", Prefix: "ER-UI", Description: "Read/write to the system clipboard failed."},
	ErrRulesServiceUnwired:        {Const: "ErrRulesServiceUnwired", Block: "UI", Prefix: "ER-UI", Description: "ui.Services.Rename/Reorder called before bootstrap wired a *core.RulesService (degraded shell)."},
	ErrUiUnknownRoute:             {Const: "ErrUiUnknownRoute", Block: "UI", Prefix: "ER-UI", Description: "Router received an unknown route string and fell back to /dashboard (logged at WARN)."},
	ErrUiViewEnter:                {Const: "ErrUiViewEnter", Block: "UI", Prefix: "ER-UI", Description: "A view's Enter() returned an error; router fell back to /dashboard with a toast."},
	ErrUiLeaveBlocked:             {Const: "ErrUiLeaveBlocked", Block: "UI", Prefix: "ER-UI", Description: "Navigation aborted because the current view's Leave() blocked on dirty-confirm (informational)."},
	ErrUiReserved21913:            {Const: "ErrUiReserved21913", Block: "UI", Prefix: "ER-UI", Description: "Reserved sentinel for the 21913–21919 router-error sub-block (spec/24-app-design-system-and-ui §03)."},
	ErrUnknown:                    {Const: "ErrUnknown", Block: "Unknown", Prefix: "ER-UNKNOWN", Description: "Sentinel — should never appear in healthy logs."},
	ErrWatcherStart:               {Const: "ErrWatcherStart", Block: "Watcher", Prefix: "ER-WCH", Description: "Watcher.Start failed before the first poll."},
	ErrWatcherPollCycle:           {Const: "ErrWatcherPollCycle", Block: "Watcher", Prefix: "ER-WCH", Description: "A single poll cycle errored (transient, retried)."},
	ErrWatcherProcessEmail:        {Const: "ErrWatcherProcessEmail", Block: "Watcher", Prefix: "ER-WCH", Description: "Per-email rule/action processing failed."},
	ErrWatcherEventPublish:        {Const: "ErrWatcherEventPublish", Block: "Watcher", Prefix: "ER-WCH", Description: "Publishing a WatchEvent to the bus failed."},
	ErrWatcherShutdown:            {Const: "ErrWatcherShutdown", Block: "Watcher", Prefix: "ER-WCH", Description: "Watcher.Stop failed to drain cleanly."},
	ErrWatchAlreadyStarted:        {Const: "ErrWatchAlreadyStarted", Block: "Watcher", Prefix: "ER-WCH", Description: "Watch.Start called while a watch is already running."},
	ErrWatchNotRunning:            {Const: "ErrWatchNotRunning", Block: "Watcher", Prefix: "ER-WCH", Description: "Watch.Stop called with no active watch."},
	ErrWatchAliasRequired:         {Const: "ErrWatchAliasRequired", Block: "Watcher", Prefix: "ER-WCH", Description: "Watch operation requires a non-empty alias argument."},
	ErrWatchSubscribeClosed:       {Const: "ErrWatchSubscribeClosed", Block: "Watcher", Prefix: "ER-WCH", Description: "Subscriber channel closed mid-stream."},
	ErrWatchAccountNotFound:       {Const: "ErrWatchAccountNotFound", Block: "Watcher", Prefix: "ER-WCH", Description: "Watch alias does not match any configured account."},
}
