// Codegen for `internal/errtrace/codes_gen.go`.
//
// Reads `internal/errtrace/codes.yaml` (the P1.1 source of truth) and
// emits a Go file declaring `RegisteredCodes`, a deterministic
// `map[Code]CodeMeta` consumed by:
//
//   - the registry test (P1.4) — every `const Err* Code = ...` in
//     `codes.go` MUST appear as a key here, and vice versa.
//   - the AST guard (P1.5) — bare string literals matching the
//     `ER-XXX-2NNNN` shape outside `internal/errtrace/` are rejected
//     unless they appear in `RegisteredCodes`.
//   - any future runtime that wants to enumerate or surface codes in
//     UI/docs without re-parsing the yaml.
//
// **Determinism.** Maps in Go iterate in randomised order, so we sort
// the emitted entries by their full code string ("ER-CFG-21001" <
// "ER-CFG-21002" < "ER-DB-21101"). That ordering is also the natural
// human reading order — diff-review of a regenerated `codes_gen.go`
// should only ever show real code additions/removals, never a churn
// of map-literal reorderings.
//
// **Run from repo root:**
//
//	nix run nixpkgs#go -- run ./internal/errtrace/codegen
//
// (Or via `go generate ./internal/errtrace/...` once P1.3 wires up
// the `//go:generate` directive.)
//
// **Why `text/template`, not `go/ast` synthesis?** The output is a
// single map literal — pure data, no control flow, no imports beyond
// the package itself. A template is shorter, clearer, and the result
// goes through `go/format` for canonical gofmt anyway, so any
// formatting drift is silently corrected.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"gopkg.in/yaml.v3"
)

// codesYAML mirrors the on-disk schema of codes.yaml. Field tags use
// lowercase keys to match the yaml file. We intentionally model only
// what the generator needs — `range` is informational and ignored.
type codesYAML struct {
	Blocks []block `yaml:"blocks"`
}

type block struct {
	Name        string `yaml:"name"`
	Prefix      string `yaml:"prefix"`
	Description string `yaml:"description"`
	Codes       []code `yaml:"codes"`
}

type code struct {
	Const       string `yaml:"const"`
	Code        string `yaml:"code"`
	Description string `yaml:"description"`
}

// emittedCode is the flat record that drives the template. We unroll
// the (block → codes) hierarchy into a single sorted slice so the
// template stays trivially readable.
type emittedCode struct {
	Const       string
	Code        string
	Block       string // human-readable block name (e.g. "Config")
	Prefix      string // ER-CFG, ER-DB, …
	Description string
}

// fileTemplate is the full contents of the generated `codes_gen.go`.
// The leading `// Code generated …` header is the canonical marker
// `go test`/`go vet` recognise to skip linters that don't understand
// generated code.
//
// We export `CodeMeta` (not `codeMeta`) because the registry test in
// P1.4 lives in `package errtrace_test` and needs the field names.
const fileTemplate = `// Code generated by internal/errtrace/codegen. DO NOT EDIT.
//
// Source: internal/errtrace/codes.yaml
// Regenerate: nix run nixpkgs#go -- run ./internal/errtrace/codegen
//
// This file is the bridge between the human-curated codes.yaml and
// runtime/test consumers. See codegen/main.go for the full contract.

package errtrace

// CodeMeta describes a single error code's static metadata. Populated
// at generate-time from codes.yaml; never mutated at runtime.
type CodeMeta struct {
	// Const is the Go identifier of the matching const in codes.go
	// (e.g. "ErrConfigOpen"). Used by the P1.4 registry test to
	// cross-check that codes.yaml and codes.go stay in sync.
	Const string

	// Block is the human-readable group name (e.g. "Config", "Store").
	// Useful for grouping codes in UI/error-registry renderings.
	Block string

	// Prefix is the ER-XXX prefix shared by every code in the block
	// (e.g. "ER-CFG"). Lets callers do prefix-matching without
	// re-parsing the Code value.
	Prefix string

	// Description is a one-line summary of when the code fires.
	// Mirrors the corresponding entry in spec/21-app/06-error-registry.md.
	Description string
}

// RegisteredCodes is the canonical set of every error code declared
// in codes.yaml. Keyed by the Code value (e.g. errtrace.ErrConfigOpen).
//
// Entries are sorted by Code string at generation time; iteration
// order over the map is still randomised by the runtime — callers
// that need deterministic order should range over a sorted key slice.
var RegisteredCodes = map[Code]CodeMeta{
{{- range .Codes }}
	{{ .Const }}: {Const: {{ printf "%q" .Const }}, Block: {{ printf "%q" .Block }}, Prefix: {{ printf "%q" .Prefix }}, Description: {{ printf "%q" .Description }}},
{{- end }}
}
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "codegen: %v\n", err)
		os.Exit(1)
	}
}

// loadCodesYAML resolves the YAML SoT path and parses it. Extracted from
// run() to keep the outer function under the 15-statement linter budget
// (AC-PROJ-20).
func loadCodesYAML() (codesYAML, string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return codesYAML{}, "", fmt.Errorf("getwd: %w", err)
	}
	yamlPath := findYAML(cwd)
	if yamlPath == "" {
		return codesYAML{}, "", fmt.Errorf("could not locate internal/errtrace/codes.yaml from cwd=%s", cwd)
	}
	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		return codesYAML{}, "", fmt.Errorf("read %s: %w", yamlPath, err)
	}
	var doc codesYAML
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return codesYAML{}, "", fmt.Errorf("parse yaml: %w", err)
	}
	outPath := filepath.Join(filepath.Dir(yamlPath), "codes_gen.go")
	return doc, outPath, nil
}

// writeFormattedSource gofmt's the rendered template and writes it to
// outPath. On gofmt failure the unformatted source is dumped to stderr so
// the real bug stays debuggable in CI (rather than silently masked).
func writeFormattedSource(outPath string, src []byte, count int) error {
	formatted, err := format.Source(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "--- raw output ---\n%s\n--- end raw ---\n", src)
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s (%d codes)\n", outPath, count)
	return nil
}

// run is the testable entry-point. main() is a thin shell so an
// external test (or `go run`) can exercise the same logic.
func run() error {
	doc, outPath, err := loadCodesYAML()
	if err != nil {
		return err
	}
	emitted, err := flatten(doc)
	if err != nil {
		return err
	}
	src, err := render(emitted)
	if err != nil {
		return fmt.Errorf("render template: %w", err)
	}
	return writeFormattedSource(outPath, src, len(emitted))
}

// findYAML walks up from `start` looking for `internal/errtrace/codes.yaml`.
// Supports the two common invocation patterns: from the repo root
// (`go run ./internal/errtrace/codegen`) and from inside the codegen
// dir itself (`cd internal/errtrace/codegen && go run .`).
func findYAML(start string) string {
	dir := start
	for i := 0; i < 8; i++ { // hard cap — repo nesting is shallow
		candidate := filepath.Join(dir, "internal", "errtrace", "codes.yaml")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		// Also try the case where cwd is already inside internal/errtrace.
		sibling := filepath.Join(dir, "codes.yaml")
		if _, err := os.Stat(sibling); err == nil &&
			filepath.Base(filepath.Dir(sibling)) == "errtrace" {
			return sibling
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
	return ""
}

// flatten collapses the (block → codes) tree into one sorted slice
// and validates uniqueness. Duplicate const identifiers or duplicate
// code strings are programmer errors — we fail loudly here rather
// than silently overwriting in the emitted map.
func flatten(doc codesYAML) ([]emittedCode, error) {
	if len(doc.Blocks) == 0 {
		return nil, fmt.Errorf("codes.yaml has zero blocks — refusing to emit empty registry")
	}
	out := make([]emittedCode, 0, 64)
	seenConst := map[string]string{} // const → first code seen
	seenCode := map[string]string{}  // code  → first const seen
	for _, b := range doc.Blocks {
		if b.Prefix == "" || b.Name == "" {
			return nil, fmt.Errorf("block missing name/prefix: %+v", b)
		}
		for _, c := range b.Codes {
			if c.Const == "" || c.Code == "" {
				return nil, fmt.Errorf("block %s has entry with empty const/code: %+v",
					b.Prefix, c)
			}
			if prev, dup := seenConst[c.Const]; dup {
				return nil, fmt.Errorf("duplicate const %q (codes %q and %q)",
					c.Const, prev, c.Code)
			}
			if prev, dup := seenCode[c.Code]; dup {
				return nil, fmt.Errorf("duplicate code %q (consts %q and %q)",
					c.Code, prev, c.Const)
			}
			seenConst[c.Const] = c.Code
			seenCode[c.Code] = c.Const
			out = append(out, emittedCode{
				Const:       c.Const,
				Code:        c.Code,
				Block:       b.Name,
				Prefix:      b.Prefix,
				Description: c.Description,
			})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Code < out[j].Code })
	return out, nil
}

// render expands the file template against the flattened code list.
func render(codes []emittedCode) ([]byte, error) {
	tmpl, err := template.New("codes_gen.go").Parse(fileTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct{ Codes []emittedCode }{codes}); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
